version: '3'

# The .env file is for production use with server-specific configurations

services:
  nginx:
    volumes:
      - ./nginx/md2k-bundle.crt:/etc/ssh/certs/ssl-cert.crt
      - ./nginx/md2k.org.key:/etc/ssh/certs/ssl-cert.key
