version: '3'

# volumes:
#   data-volume:

services:

  nginx:
    

  # cc-flask:
  #   build: ../CerebralCortex-CerebralCortex-API
  #   ports:
  #     - "80:80"


  kafka:
    image: "spotify/kafka"

  spark-notebook:
    image: "jupyter/all-spark-notebook"
    ports:
      - "8888:8888"
    container_name: spark-notebook
    restart: always
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
    # depends_on:
    #   - db
    #   - redis
    # links:
    #   - ??
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://192.168.0.42:123"


  # cassandra:
  #   image: "cassandra:3.9"
  #   ports:
  #     - "9160:9160" # Thrift client API
  #     - "9042:9042" # CQL native transport
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=cerebralcortex
  #
  # mysql:
  #   image: "mysql:5.7"
  #   ports:
  #     - "3306:3306" # Default mysql port
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=random_root_password
  #     - MYSQL_DATABASE=cerebralcortex
  #     - MYSQL_USER=cerebralcortex
  #     - MYSQL_PASSWORD=cerebralcortex_pass
