version: '3'

services:
# Frontend web proxy for accessing services and providing TLS encryption
  nginx:
    build: ./nginx
    container_name: md2k-nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - grafana
      - jupyter
    # depends_on:
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.nginx


# Unified logging infrastructure for containers
  # fluentd:
  #   build: ./fluentd
  #   links:
  #     - "elasticsearch"
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #
  # elasticsearch:
  #   image: elasticsearch
  #   container_name: md2k-elasticsearch
  #   expose:
  #     - 9200
  #   ports:
  #     - "9200:9200"
  #
  # kibana:
  #   image: kibana
  #   container_name: md2k-kibana
  #   links:
  #     - "elasticsearch"
  #   ports:
  #     - "5601:5601"


# Data vizualizations
  grafana:
    image: "grafana/grafana"
    container_name: md2k-grafana
    ports:
      - "3000:3000"
    # links:
    #   - influxdb
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      # - GF_INSTALL_PLUGINS=raintank-worldping-app,grafana-clock-panel,grafana-simple-json-datasource
    # depends_on:
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.grafana

  # influxdb:
  #   image: "influxdb:1.2"
  #   container_name: md2k-influxdb
  #   ports:
  #     - "8086:8086"
    # depends_on:
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.influxdb


# Data Science Dashboard Interface
  jupyter:
    image: "jupyter/all-spark-notebook"
    ports:
      - "8888:8888"
    container_name: md2k-spark-notebook
    restart: always
    environment:
      # - PASSWORD=${PASSWORD}
      - PASSWORD=md2k
    # depends_on:
    #   - cc-flask
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.spark-notebook





# Cerebral Cortex API server
  # cc-flask:
  #   build: ../CerebralCortex-CerebralCortex-API
  #   container_name: md2k-cc-api
  #   ports:
  #     - "8080:80"
  #   restart: always
  #   depends_on:
  #     - mysql
  #     - cassandra
  #     - kafka
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.cc-api


# Cerebral Cortex backend
  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: md2k-kafka
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  #     KAFKA_CREATE_TOPICS: "cc-test-topic:3:1:compact"
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - zookeeper
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.kafka

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: md2k-zookeeper
  #   ports:
  #     - "2181:2181"
    # depends_on:
    #   - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: org.md2k.kafka


  # cassandra:
  #   # image: "cassandra:3.9"
  #   build: ./cassandra
  #
  #   container_name: md2k-cassandra
  #   restart: always
  #   ports:
  #     - "9160:9160" # Thrift client API
  #     - "9042:9042" # CQL native transport
  #   # expose:
  #   #   - "9160"
  #   #   - "9042"
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=cerebralcortex
  #   # depends_on:
  #   #   - fluentd
  #   # logging:
  #   #   driver: fluentd
  #   #   options:
  #   #     fluentd-address: localhost:24224
  #   #     tag: org.md2k.cassandra
  #
  # mysql:
  #   image: "mysql:5.7"
  #   container_name: md2k-mysql
  #   restart: always
  #   ports:
  #     - "3306:3306" # Default mysql port
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=random_root_password
  #     - MYSQL_DATABASE=cerebralcortex
  #     - MYSQL_USER=cerebralcortex
  #     - MYSQL_PASSWORD=cerebralcortex_pass
  #   volumes:
  #     - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  #   # depends_on:
  #   #   - fluentd
  #   # logging:
  #   #   driver: fluentd
  #   #   options:
  #   #     fluentd-address: localhost:24224
  #   #     tag: org.md2k.mysql
